#!/usr/bin/env python3
"""Generate the functionality inventory from the actual CLI tree.

REL-05 asks for a checked-in inventory of every public command, its flags, what it writes
and what it needs. Written by hand that list is wrong within a month: a flag is renamed, a
subcommand is added, and the document quietly describes a tool that no longer exists — which
is worse than no document, because people trust it.

So it is generated. The tree comes from ``cli.build_parser()``, which is the same parser
``--help`` prints and the same one the commands actually run under; the effect and
capability columns come from ``cli.SUPPORT``, which ``tests/test_inventory.py`` holds level
with the tree. Adding a command without declaring what it writes fails the suite.

    python scripts/inventory.py            # write docs/INVENTORY.md
    python scripts/inventory.py --check    # exit 1 if the checked-in file is stale
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from coreyard import __version__, cli  # noqa: E402

OUTPUT = Path(__file__).resolve().parent.parent / "docs" / "INVENTORY.md"

HEADER = """# CoreYard functionality inventory

Generated by `scripts/inventory.py` from the live command tree — do not edit by hand.
Run `python scripts/inventory.py` after changing a command, and `--check` in CI.

Every public command appears here with what it changes and what it needs, because a
command with an undocumented support status cannot be qualified for release (REL-01) and
cannot be inventoried (REL-05).

**Effect** is the *most* this command can do, not what it does by default. Where a write
is gated, the **Unlocked by** column names the flag; without it the command reports and
changes nothing outside `out/`. `--dry-run` is accepted throughout and always means
"decide, report, change nothing".

**Needs** names the capabilities from `coreyard/capabilities.py` that the command cannot
run without. `coreyard doctor` reports which of them this installation has. A blank cell
means the command works on any supported installation.
"""

LEGACY = """
## Legacy entry points

Every command below is also reachable as `python -m <module>`, and those paths are still
tested. This installation's crontab named them for a long time, and a scheduled job that
changes behaviour silently costs a day before anyone notices. The one deliberate
difference: `coreyard sync` defaults to `--sink api`, while the legacy `coreyard.run_sync`
entry point keeps its original `csv` default.
"""


def _subparsers(parser):
    return next((a for a in parser._actions
                 if isinstance(a, argparse._SubParsersAction)), None)


def _help_texts(parser) -> dict:
    action = _subparsers(parser)
    return {choice.dest: (choice.help or "")
            for choice in (action._choices_actions if action else [])}


def walk(parser=None) -> list[dict]:
    """Every node of the tree, with its help, flags and whether it has children.

    The traversal itself is ``cli.tree`` — the same one the preflight uses to decide what a
    command needs. Two walkers would eventually disagree, and then this document would
    describe a tool the code does not enforce.
    """
    parser = parser or cli.build_parser()
    helps: dict[str, str] = {}
    for path, node in [("", parser)] + cli.tree(parser):
        for name, text in _help_texts(node).items():
            helps[f"{path} {name}".strip()] = text
    rows: list[dict] = []
    for path, node in cli.tree(parser):
        flags = sorted({option for act in node._actions for option in act.option_strings
                        if option.startswith("--") and option != "--help"})
        rows.append({"path": path, "help": helps.get(path, ""), "flags": flags,
                     "children": bool(_subparsers(node))})
    return rows


def _escape(text: str) -> str:
    return text.replace("|", "\\|").replace("\n", " ").strip()


def render() -> str:
    rows = walk()
    lines = [HEADER, f"\nCoreYard {__version__} — {len(rows)} commands.\n",
             "| Command | What it does | Effect | Unlocked by | Needs |",
             "|---|---|---|---|---|"]
    for row in rows:
        effect, needs, gate = cli.SUPPORT.get(row["path"], ("UNDOCUMENTED", (), ""))
        name = f"`coreyard {row['path']}`"
        lines.append(f"| {name} | {_escape(row['help'])} | {effect} | "
                     f"{'`' + gate + '`' if gate else ''} | {', '.join(needs)} |")
    lines.append("\n## Flags, by command\n")
    for row in rows:
        if row["children"]:
            continue
        flags = " ".join(f"`{flag}`" for flag in row["flags"]) or "_(no options)_"
        lines.append(f"- **`coreyard {row['path']}`** — {flags}")
    lines.append(LEGACY)
    return "\n".join(lines) + "\n"


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true",
                        help="exit 1 if the checked-in inventory is out of date")
    args = parser.parse_args(argv)
    text = render()
    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != text:
            print(f"{OUTPUT} is out of date — run `python scripts/inventory.py`",
                  file=sys.stderr)
            return 1
        print(f"{OUTPUT.name} is up to date.")
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUTPUT} ({len(text.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
